### ISSUE TITLE
PHP 7.4 Deprecated Array and string offset access syntax with curly braces

### ISSUE THREAD

**Issue by yoyonsugiono** [RoNoLo/jsonextract#1]
CJSON.php

`$ord_var_c = ord($var{$c});`

**Comment by emanaton** [comment]
Sooo we've waited long enough for this fix, eh? I've just forked the repo, fixed the problem, and [committed a PR back to this repo with that fix](https://github.com/RoNoLo/json-extract/pull/2). In the meantime, you can install a working version via my fork if you want: https://github.com/emanaton/json-extract
